# Generated by Django 3.2.16 on 2022-12-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('creation_date', models.DateField(verbose_name='Creation_Date')),
                ('deadline', models.DateField(verbose_name='Deadline')),
            ],
        ),
    ]
