# Generated by Django 3.2.16 on 2022-12-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_options_notes_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='state',
        ),
    ]
