# Generated by Django 3.2.16 on 2022-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20221212_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
